### ISSUE TITLE
The mnemonics in the README is incorrect

### ISSUE THREAD

**Issue by jermay** [Ivan-on-Tech-Academy/academy-cryptokitties#1]
The mnemonic in the readme says:

`gesture rather obey video awake genuine patient base soon parrot upset lounge`

but the mnemonic in the `truffle-config` for networks  `ganache` and `development` is defined as:

`mountain mango ivory image attitude rebuild gorilla until canoe feed flat parrot`

Please pick one or the other and update accordingly. Thanks!

**Comment by gabkk** [comment]
We will use the first one now thanks
