### ISSUE TITLE
Repeated Functions

### ISSUE THREAD

**Issue by wafflemakr** [Ivan-on-Tech-Academy/academy-cryptokitties#2]
[getKittyByOwner](https://github.com/Ivan-on-Tech-Academy/academy-cryptokitties/blob/dev/contracts/KittyCore.sol#L27) and [tokensOfOwner](https://github.com/Ivan-on-Tech-Academy/academy-cryptokitties/blob/dev/contracts/KittyOwnership.sol#L110) return the same result.

**Comment by gabkk** [comment]
yes true , tokensOfOwner is mandatory to be erc 721 compliant, but i think we ll remove the getKittyByOwner
:+1:

**Comment by gabkk** [comment]
Solved
1ec446d1cf5235178316aac2db204a13c825e0f9
